services:
  ###############################################################################
  # NORDVPN CLI: Official NordVPN Client Container
  ###############################################################################
  nordvpn:
    container_name: nordvpn_official
    build:
      context: ./docker/nordvpn-cli
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
      - net.ipv6.conf.all.forwarding=1
    environment:
      - NORDVPN_USER=${NORDVPN_USER}
      - NORDVPN_PASS=${NORDVPN_PASS}
      - TECHNOLOGY=${NORDVPN_TECH:-NordLynx}
      - NETWORK=${LOCAL_NETWORK:-192.168.0.0/16}
      - TZ=${TZ:-UTC}
    ports:
      # Prowlarr Web UI (through VPN)
      - "${PORT_PROWLARR:-9696}:9696"
      # FlareSolverr API (through VPN)
      - "8191:8191"
      # qBittorrent Web UI (through VPN)
      - "${PORT_QBITTORRENT:-8080}:8080"
    volumes:
      - /lib/modules:/lib/modules:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "true"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      ai-media-network:
        aliases:
          - prowlarr

  ###############################################################################
  # PROWLARR: Indexer Management (VPN Protected via NordVPN CLI)
  ###############################################################################
  prowlarr:
    container_name: ai_media_prowlarr
    image: lscr.io/linuxserver/prowlarr:${PROWLARR_VERSION:-latest}
    network_mode: "service:nordvpn"
    depends_on:
      nordvpn:
        condition: service_started
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${CONFIG_PROWLARR:-./config/prowlarr}:/config
      - ${LOGS_PATH:-./logs}/prowlarr:/logs
    restart: unless-stopped

  ###############################################################################
  # FLARESOLVERR: CloudFlare Bypass (VPN Protected via NordVPN CLI)
  ###############################################################################
  flaresolverr:
    container_name: ai_media_flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    network_mode: "service:nordvpn"
    depends_on:
      nordvpn:
        condition: service_started
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ:-UTC}
      - CAPTCHA_SOLVER=none
    restart: unless-stopped

  ###############################################################################
  # MCP SERVER: Prowlarr & qBittorrent MCP Server (SEPARATE NETWORK - NO VPN)
  ###############################################################################
  mcp-server:
    container_name: ai_media_mcp_server
    build:
      context: ./mcp-server
      dockerfile: Dockerfile
    depends_on:
      nordvpn:
        condition: service_started
      qbittorrent:
        condition: service_started
    environment:
      # Connect to Prowlarr via VPN container IP
      - PROWLARR_URL=http://prowlarr:9696
      - PROWLARR_API_KEY=${PROWLARR_API_KEY}
      # Connect to qBittorrent via VPN container IP  
      - QBITTORRENT_URL=http://qbittorrent:8080
      - QBITTORRENT_USERNAME=${QBITTORRENT_USERNAME:-admin}
      - QBITTORRENT_PASSWORD=${QBITTORRENT_PASSWORD:-adminpass}
      - QBITTORRENT_SESSION_TIMEOUT=${QBITTORRENT_SESSION_TIMEOUT:-3600}
      - TZ=${TZ:-UTC}
      - MCP_PORT=3000
      - NODE_ENV=production
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      # MCP Server API (direct host access - NO VPN)
      - "${MCP_PORT:-3000}:3000"
    networks:
      - ai-media-network
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: ["node", "dist/mcp-server.js", "--http"]

  ###############################################################################
  # QBITTORRENT: Torrent Client (VPN Protected via NordVPN CLI)
  ###############################################################################
  qbittorrent:
    container_name: ai_media_qbittorrent
    image: lscr.io/linuxserver/qbittorrent:${QBITTORRENT_VERSION:-latest}
    network_mode: "service:nordvpn"
    depends_on:
      nordvpn:
        condition: service_started
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - WEBUI_PORT=${PORT_QBITTORRENT:-8080}
      - DOCKER_MODS=linuxserver/mods:qbittorrent-vuetorrent
      - WEBUI_USERNAME=${QBITTORRENT_USERNAME:-admin}
      - WEBUI_PASSWORD=${QBITTORRENT_PASSWORD:-adminpass}
    volumes:
      - ${CONFIG_QBITTORRENT:-./config/qbittorrent}:/config
      - ${DOWNLOADS_PATH:-./downloads}:/downloads
      - ${MEDIA_PATH:-./media}:/media
      - ${LOGS_PATH:-./logs}/qbittorrent:/logs
    restart: unless-stopped

  ###############################################################################
  # FILEBROWSER: File Management Web Interface
  ###############################################################################
  filebrowser:
    container_name: ai_media_filebrowser
    image: filebrowser/filebrowser:${FILEBROWSER_VERSION:-latest}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - ${CONFIG_FILEBROWSER:-./config/filebrowser}:/database
      - ${MEDIA_PATH:-./media}:/srv/media:ro
      - ${DOWNLOADS_PATH:-./downloads}:/srv/downloads:rw
      - ${CONFIG_PATH:-./config}:/srv/config:ro
      - ${LOGS_PATH:-./logs}:/srv/logs:ro
    ports:
      - "${PORT_FILEBROWSER:-8081}:80"
    restart: unless-stopped
    command:
      - --database=/database/filebrowser.db
      - --root=/srv
      - --address=0.0.0.0

###############################################################################
# NETWORKS: Custom bridge network for inter-container communication
###############################################################################
networks:
  ai-media-network:
    driver: bridge 