services:
  ###############################################################################
  # NORDVPN CLI: Official NordVPN Client Container
  ###############################################################################
  nordvpn:
    container_name: nordvpn_official
    build:
      context: ./docker/nordvpn-cli
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
      - net.ipv6.conf.all.forwarding=1
    environment:
      - NORDVPN_USER=${NORDVPN_USER}
      - NORDVPN_PASS=${NORDVPN_PASS}

      - TECHNOLOGY=${NORDVPN_TECH:-NordLynx}
      - NETWORK=${LOCAL_NETWORK:-192.168.0.0/16}
      - TZ=${TZ:-UTC}
    ports:
      # Prowlarr Web UI (through VPN)
      - "${PORT_PROWLARR:-9696}:9696"
      # FlareSolverr API (through VPN)
      - "8191:8191"
      # qBittorrent Web UI (through VPN)
      - "${PORT_QBITTORRENT:-8080}:8080"
    volumes:
      - /lib/modules:/lib/modules:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "true"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

  ###############################################################################
  # PROWLARR: Indexer Management (VPN Protected via NordVPN CLI)
  ###############################################################################
  prowlarr:
    container_name: ai_media_prowlarr
    image: lscr.io/linuxserver/prowlarr:${PROWLARR_VERSION:-latest}
    network_mode: "service:nordvpn"
    depends_on:
      nordvpn:
        condition: service_started
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${CONFIG_PROWLARR:-./config/prowlarr}:/config
      - ${LOGS_PATH:-./logs}/prowlarr:/logs
    restart: unless-stopped

  ###############################################################################
  # FLARESOLVERR: CloudFlare Bypass (VPN Protected via NordVPN CLI)
  ###############################################################################
  flaresolverr:
    container_name: ai_media_flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    network_mode: "service:nordvpn"
    depends_on:
      nordvpn:
        condition: service_started
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ:-UTC}
      - CAPTCHA_SOLVER=none
    restart: unless-stopped

  ###############################################################################
  # MCP SERVER: Prowlarr MCP Server (VPN Network Access)
  ###############################################################################
  mcp-server:
    container_name: ai_media_mcp_server
    build:
      context: ./mcp-server
      dockerfile: Dockerfile
    network_mode: "service:nordvpn"
    depends_on:
      nordvpn:
        condition: service_started
      prowlarr:
        condition: service_started
    environment:
      - PROWLARR_URL=http://localhost:9696
      - PROWLARR_API_KEY=${PROWLARR_API_KEY:-44b56a79a82d4295a367713457e6b074}
      - TZ=${TZ:-UTC}
    volumes:
      - ./mcp-server:/app:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro # For VPN management
    restart: unless-stopped
    stdin_open: true # For MCP stdio communication
    tty: true
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://localhost:9696/ping", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  ###############################################################################
  # OTHER SERVICES: Run on local network (same as current setup)
  ###############################################################################
  radarr:
    container_name: ai_media_radarr
    image: lscr.io/linuxserver/radarr:${RADARR_VERSION:-latest}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${CONFIG_RADARR:-./config/radarr}:/config
      - ${DOWNLOADS_PATH:-./downloads}:/downloads
      - ${MEDIA_PATH:-./media}:/media
      - ${LOGS_PATH:-./logs}/radarr:/logs
    ports:
      - "${PORT_RADARR:-7878}:7878"
    restart: unless-stopped

  qbittorrent:
    container_name: ai_media_qbittorrent
    image: lscr.io/linuxserver/qbittorrent:${QBITTORRENT_VERSION:-latest}
    network_mode: "service:nordvpn"
    depends_on:
      nordvpn:
        condition: service_started
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - WEBUI_PORT=${PORT_QBITTORRENT:-8080}
      - DOCKER_MODS=linuxserver/mods:qbittorrent-vuetorrent
      - WEBUI_USERNAME=${QBITTORRENT_USERNAME:-admin}
      - WEBUI_PASSWORD=${QBITTORRENT_PASSWORD:-adminpass}
    volumes:
      - ${CONFIG_QBITTORRENT:-./config/qbittorrent}:/config
      - ${DOWNLOADS_PATH:-./downloads}:/downloads
      - ${MEDIA_PATH:-./media}:/media
      - ${LOGS_PATH:-./logs}/qbittorrent:/logs
    restart: unless-stopped

  overseerr:
    container_name: ai_media_overseerr
    image: sctx/overseerr:${OVERSEERR_VERSION:-latest}
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ:-UTC}
      - PORT=${PORT_OVERSEERR:-5055}
    volumes:
      - ${CONFIG_OVERSEERR:-./config/overseerr}:/app/config
      - ${LOGS_PATH:-./logs}/overseerr:/app/logs
    ports:
      - "${PORT_OVERSEERR:-5055}:5055"
    restart: unless-stopped

  filebrowser:
    container_name: ai_media_filebrowser
    image: filebrowser/filebrowser:${FILEBROWSER_VERSION:-latest}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - ${CONFIG_FILEBROWSER:-./config/filebrowser}:/database
      - ${MEDIA_PATH:-./media}:/srv/media:ro
      - ${DOWNLOADS_PATH:-./downloads}:/srv/downloads:rw
      - ${CONFIG_PATH:-./config}:/srv/config:ro
      - ${LOGS_PATH:-./logs}:/srv/logs:ro
    ports:
      - "${PORT_FILEBROWSER:-8081}:80"
    restart: unless-stopped
    command:
      - --database=/database/filebrowser.db
      - --root=/srv
      - --address=0.0.0.0
